---
- name: (RHEL 7) Install GeoIP2 dependency
  when:
    - (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] is version('7', '=='))
    - '"geoip2" in nginx_modules'
  block:
    - name: (RHEL 7) Check if libmaxminddb is available
      ansible.builtin.yum:
        list: available
      register: packages

    - name: (RHEL 7) Install libmaxminddb
      ansible.builtin.yum:
        name: https://rpmfind.net/linux/centos/7.9.2009/os/x86_64/Packages/libmaxminddb-1.2.0-6.el7.x86_64.rpm
      when: "'libmaxminddb' not in packages['results']"

- name: (RHEL) Install GeoIP2 and/or OpenTracing EPEL dependency
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ('opentracing' in nginx_modules)
    - nginx_install_epel_release | bool
  block:
    - name: (RHEL) Import EPEL GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ((ansible_facts['distribution'] == 'Amazon') | ternary('7', ansible_facts['distribution_major_version'])) }}

    - name: (RHEL) Install EPEL
      ansible.builtin.yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ((ansible_facts['distribution'] == 'Amazon') | ternary('7', ansible_facts['distribution_major_version'])) }}.noarch.rpm

- name: Install NGINX modules
  ansible.builtin.package:
    name: "nginx-{{ (nginx_type == 'plus') | ternary('plus-', '') }}module-{{ item['name'] | default(item) }}
    state: "{{ item['state'] | default('present') }}"
  loop: "{{ nginx_modules }}"
  when:
    - (item['name'] | default(item) in nginx_modules_list and nginx_type == 'opensource')
      or (item['name'] | default(item) in nginx_plus_modules_list and nginx_type == 'plus')
    - not (item['name'] | default(item) == "geoip")
      or (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] is version('8', '>=')))
