---
- name: (Amazon Linux/CentOS/Oracle Linux/RHEL) Install logrotate
  ansible.builtin.yum:
    name: logrotate
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: Create logrotate config
  ansible.builtin.template:
    src: logrotate/nginx.j2
    dest: /etc/logrotate.d/nginx
    mode: "0644"
  notify: (Handler) Run logrotate
